#:import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspective_points_x: self.width/2
    perspective_points_y: self.height * 0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_text
        font_size: dp(30)
        font_name: 'fonts/Eurostile.ttf'
        size_hint: .18, .18
        pos_hint: {"x": 0, "top": 1}